<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Title is not Matching]]>
    </line>
    <line>
      <![CDATA[Element is present]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="67755" started-at="2017-08-17T12:58:27Z" finished-at="2017-08-17T12:59:35Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="67755" started-at="2017-08-17T12:58:27Z" finished-at="2017-08-17T12:59:35Z">
      <class name="com.automation.test.ValidLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.ValidLogin@3b1d11]" name="openApplication" is-config="true" duration-ms="12741" started-at="2017-08-17T18:28:27Z" finished-at="2017-08-17T18:28:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testValidLogin()[pri:1, instance:com.automation.test.ValidLogin@3b1d11]" name="testValidLogin" duration-ms="12890" started-at="2017-08-17T18:28:40Z" finished-at="2017-08-17T18:28:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at generic.BasePage.verifyTitle(BasePage.java:23)
	at com.automation.test.ValidLogin.testValidLogin(ValidLogin.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Title is not Matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.ValidLogin@3b1d11]" name="closeApplication" is-config="true" duration-ms="1577" started-at="2017-08-17T18:28:53Z" finished-at="2017-08-17T18:28:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.ValidLogin -->
      <class name="com.automation.test.InvalidLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.InvalidLogin@fc185]" name="openApplication" is-config="true" duration-ms="11297" started-at="2017-08-17T18:28:54Z" finished-at="2017-08-17T18:29:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="PASS" signature="testInvalidLogin()[pri:2, instance:com.automation.test.InvalidLogin@fc185]" name="testInvalidLogin" duration-ms="5038" started-at="2017-08-17T18:29:06Z" finished-at="2017-08-17T18:29:11Z">
          <reporter-output>
            <line>
              <![CDATA[Element is present]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.InvalidLogin@fc185]" name="closeApplication" is-config="true" duration-ms="861" started-at="2017-08-17T18:29:11Z" finished-at="2017-08-17T18:29:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.InvalidLogin -->
      <class name="com.automation.test.verifyProductVersion">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.verifyProductVersion@f5e5e3]" name="openApplication" is-config="true" duration-ms="10716" started-at="2017-08-17T18:29:12Z" finished-at="2017-08-17T18:29:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testProductVersion()[pri:3, instance:com.automation.test.verifyProductVersion@f5e5e3]" name="testProductVersion" duration-ms="11672" started-at="2017-08-17T18:29:22Z" finished-at="2017-08-17T18:29:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [actiTIME 2017.1] but found [Product Version:]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [actiTIME 2017.1] but found [Product Version:]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.automation.page.EnterTimeTrackPage.verifyVersion(EnterTimeTrackPage.java:36)
	at com.automation.test.verifyProductVersion.testProductVersion(verifyProductVersion.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductVersion -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.verifyProductVersion@f5e5e3]" name="closeApplication" is-config="true" duration-ms="759" started-at="2017-08-17T18:29:34Z" finished-at="2017-08-17T18:29:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.verifyProductVersion -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
